# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            BitShares Committee
tagline:          'A Jekyll theme for Bitshares Committee news and proposals aggregation'
description:      'News, proposals, suggestions & notifications from the BitShares Committee.'
url:              http://bc.clockwork.gr
baseurl:          /
repository:       'clockworkgr/github.com'
author:
  name:           'BitShares Committee'
  url:            https://github.com/bitshares-commitee

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/clockworkgr/bc
